name:
  adv-db-systems

volumes:
  memgraph_data:

services:
  memgraph:
    image: memgraph/memgraph-mage:latest
    container_name: adv-db-systems.memgraph
    pull_policy: always
    ports:
      - "7687:7687"
      - "7444:7444"
    volumes:
      - memgraph_data:/var/lib/memgraph
      - ./data:/data
    environment:
      MEMGRAPH_LOG_LEVEL: info
    restart: unless-stopped

  memgraph-lab:
    image: memgraph/lab:latest
    container_name: adv-db-systems.memgraph-lab
    pull_policy: always
    ports:
      - "3000:3000"
    environment:
      QUICK_CONNECT_MG_HOST: memgraph
      QUICK_CONNECT_MG_PORT: 7687
    depends_on:
      - memgraph
    restart: unless-stopped
